In [39]:
#Nhilbert Jay E. Valente
#CMSC 197
#Quiz 1

In [1]:
import numpy as np

In [10]:
#Part1 of the Assignment

In [12]:
#Initializing y_hat with 20 linearly spaced numbers between -1 and 1
y_hat = np.linspace(-1, 1, num=20) 

In [8]:
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [13]:
#Initializing y with 20 linearly spaced numbers between 0 and 1
y = np.linspace(0, 1, num=20)

In [9]:
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [14]:
#Dimensions of y_hat
y_hat.ndim

1

In [15]:
#Dimensions of y
y.ndim

1

In [16]:
#Shape of y_hat
y_hat.shape

(20,)

In [17]:
#Shape of y
y.shape

(20,)

In [44]:
#Create individual functions for each of the loss functions with y and y_hat as parameters and return the loss value

In [97]:
#Mean Squared Error
MSE = np.square(np.subtract(y_hat,y)).mean()

In [123]:
#Loss value of Mean Squared Error
L = MSE
print(L)

0.3421052631578948


In [121]:
#Mean Absolute Error
n = 20
sum = 0
  
# for loop for iteration
for i in range(n):
    sum += abs(y_hat[i] - y[i])
  
error = sum/n
MAE = float(error)

In [122]:
#Loss value of Mean Absolute Error
L = MAE
print(L)

0.5000000000000001


In [125]:
#Mean Squared Logarithmic Error
for i in range(n):
    sum1 = y_hat[i]+1
sum2 = y+1
log1 = np.log(sum1)
log2 = np.log(sum2)
MSLE = np.square(np.subtract(log1,log2)).mean()

In [126]:
#Loss value of Mean Squared Logarithmic Error
L = float(MSLE)
print(L)

0.13890524984448185


In [131]:
#Mean Absolute Percentage Error
A = y_hat - y
B = y

n = 20
for i in range(n):
    sum += abs(A/B)
    
error = 1.00/20
MAPE = error*sum

C:\Users\JAY\AppData\Local\Temp\ipykernel_9684\2528451273.py:7: RuntimeWarning: divide by zero encountered in true_divide
  sum += abs(A/B)


In [133]:
#Loss Value of Mean Absolute Percentage Error
L = MAPE
print(L)

[inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf]


In [117]:
#Part 2 of the Assignment

In [118]:
#Creating a 1D array M {1, 2, …16} using the arange function
M = np.arange(start=1, stop=17, step=1)

In [22]:
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [23]:
#Reshaping M into 4x4 array and storing it to N
N = M.reshape(4, 4)

In [24]:
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
#Getting the 2nd row of N
print (N[1, :])

[5 6 7 8]


In [30]:
#Minimum values for each column in N
np.amin(N, axis=0)

array([1, 2, 3, 4])

In [34]:
#Location of minimum values for each column of N
result = np.where(N == np.amin(N, axis=0))
location = list(zip(result[0], result[1]))
for cord in location:
    print(cord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [35]:
#The average of the whole matrix
N.mean()

8.5

In [36]:
#Create a vector V with 4 elements, each element is 1
V = [1, 1, 1, 1]

In [37]:
V

[1, 1, 1, 1]

In [38]:
#The dot product of N and V
np.dot(N, V)

array([10, 26, 42, 58])